July 1st, 2026

Combine EM results with assertions data - *relative corroboration*

Notebook re-ran and updated as of **July 24, 2026**

*Import packages and modifying data*

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read in predictions
preds = pd.read_csv("../predictions.csv")
# Read in assertions data
assertions = pd.read_csv("../assertions/assertions_clean.csv")

**Takes 40s to load in because there is so much data**

In [3]:
# Take a subset of columns in preds (probability and unique ids)
# Theoretically, you only need the probability and the unique ids for boosting
matches = preds[['match_probability', 'unique_id_l', 'unique_id_r']]
# Write out matches to CSV for better storage
matches.to_csv('matches.csv', index=False)

In [4]:
# Get all relatives for each mention_id (both directions)
relatives_l = assertions[['subject_id', 'object_id']].rename(columns={'subject_id': 'mention_id', 'object_id': 'relative_id'})
relatives_r = assertions[['object_id', 'subject_id']].rename(columns={'object_id': 'mention_id', 'subject_id': 'relative_id'})
# Combine both directions
all_relatives = pd.concat([relatives_l, relatives_r]).drop_duplicates()
# Build a dict: mention_id -> set of relative ids
relative_sets = all_relatives.groupby('mention_id')['relative_id'].apply(set).to_dict()

*Look at the data*

In [5]:
matches

          match_probability        unique_id_l       unique_id_r
0                  0.999702  ALB-CN-1870-10570  ALB-CN-1880-6166
1                  0.999702  ALB-CN-1870-12185  ALB-CN-1880-6171
2                  0.999702  ALB-CN-1870-14277  ALB-CN-1880-6173
3                  0.999702  ALB-CN-1870-18074  ALB-CN-1880-6174
4                  0.999702  ALB-CN-1870-14278  ALB-CN-1880-6175
...                     ...                ...               ...
28635362           0.963258   ALB-CN-1870-5722  ALB-CN-1880-1742
28635363           0.394037   ALB-CN-1870-5722  ALB-CN-1880-1878
28635364           0.394037   ALB-CN-1870-5722  ALB-CN-1880-3138
28635365           0.394037   ALB-CN-1870-5722  ALB-CN-1880-3184
28635366           0.999702   ALB-CN-1870-5722  ALB-CN-1880-3226

[28635367 rows x 3 columns]

In [6]:
all_relatives

              mention_id        relative_id
0          ALB-CN-1870-1      ALB-CN-1870-4
1         ALB-CN-1870-14     ALB-CN-1870-16
2         ALB-CN-1870-22     ALB-CN-1870-24
3         ALB-CN-1870-33     ALB-CN-1870-35
4         ALB-CN-1870-33     ALB-CN-1870-39
...                  ...                ...
56076  ALB-CN-1880-19147  ALB-CN-1880-19146
56077  ALB-CN-1880-10085  ALB-CN-1880-10084
56078  ALB-CN-1880-17516  ALB-CN-1880-17515
56079   ALB-CN-1880-3805   ALB-CN-1880-3804
56080  ALB-CN-1880-22747  ALB-CN-1880-22746

[79797 rows x 2 columns]

*Get relatives for each left and right record*

In [7]:
# Map relative sets onto matches for each side
matches['relatives_l'] = matches['unique_id_l'].map(relative_sets)
matches['relatives_r'] = matches['unique_id_r'].map(relative_sets)

*Get relative_probs*

`relative_probs` is calculated as follows:
For each potential pair in **matches**:
- Check whether the `unique_id_l` (1870 mention id) has relatives
    - If they don't have relatives, set `relatives_match_probability` as **NA** 
    - If they do have relatives look through each potential combination of `relatives_l` and `relatives_r`:
        - Look through **match_lookup** for the `match_probability` (from the EM model) and:
            - Take the maximum "match" probability for each `relatives_l`
            - Average all the probability values for `relatives_match_probability`

In [8]:
# Build match lookup dict
match_lookup = matches.set_index(['unique_id_l', 'unique_id_r'])['match_probability'].to_dict()

In [9]:
match_lookup

{('ALB-CN-1870-10570', 'ALB-CN-1880-6166'): 0.9997020953520708,
 ('ALB-CN-1870-12185', 'ALB-CN-1880-6171'): 0.9997020953520708,
 ('ALB-CN-1870-14277', 'ALB-CN-1880-6173'): 0.9997020953520708,
 ('ALB-CN-1870-18074', 'ALB-CN-1880-6174'): 0.9997020953520708,
 ('ALB-CN-1870-14278', 'ALB-CN-1880-6175'): 0.9997020953520708,
 ('ALB-CN-1870-17938', 'ALB-CN-1880-6177'): 0.9997020953520708,
 ('ALB-CN-1870-11669', 'ALB-CN-1880-618'): 0.9997020953520708,
 ('ALB-CN-1870-19009', 'ALB-CN-1880-6181'): 0.9997020953520708,
 ('ALB-CN-1870-8867', 'ALB-CN-1880-6182'): 0.9997020953520708,
 ('ALB-CN-1870-7510', 'ALB-CN-1880-6183'): 0.9997020953520708,
 ('ALB-CN-1870-8867', 'ALB-CN-1880-6184'): 0.9997020953520708,
 ('ALB-CN-1870-12545', 'ALB-CN-1880-6185'): 0.9999530711793492,
 ('ALB-CN-1870-14999', 'ALB-CN-1880-6189'): 0.9999530711793492,
 ('ALB-CN-1870-15100', 'ALB-CN-1880-6190'): 0.9997020953520708,
 ('ALB-CN-1870-21610', 'ALB-CN-1880-6197'): 0.9999926088816468,
 ('ALB-CN-1870-14484', 'ALB-CN-1880-6199'): 0.9997020953520708,
 ('ALB-CN-1870-9703', 'ALB-CN-1880-62'): 0.9997020953520708,
 ('ALB-CN-1870-21616', 'ALB-CN-1880-6200'): 0.9997020953520708,
 ('ALB-CN-1870-3255', 'ALB-CN-1880-6202'): 0.9997020953520708,
 ('ALB-CN-1870-5517', 'ALB-CN-1880-6203'): 0.9997020953520708,
 ('ALB-CN-1870-15039', 'ALB-CN-1880-6206'): 0.9997020953520708,
 ('ALB-CN-1870-15045', 'ALB-CN-1880-6208'): 0.9999999909059626,
 ('ALB-CN-1870-15039', 'ALB-CN-1880-6209'): 0.9999999909059626,
 ('ALB-CN-1870-15034', 'ALB-CN-1880-6210'): 0.9999530711793492,
 ('ALB-CN-1870-15305', 'ALB-CN-1880-6228'): 0.9999999909059626,
 ('ALB-CN-1870-20837', 'ALB-CN-1880-6229'): 0.9997020953520708,
 ('ALB-CN-1870-14756', 'ALB-CN-1880-6230'): 0.9997020953520708,
 ('ALB-CN-1870-15401', 'ALB-CN-1880-6233'): 0.9999999909059626,
 ('ALB-CN-1870-2705', 'ALB-CN-1880-625'): 0.9997020953520708,
 ('ALB-CN-1870-14783', 'ALB-CN-1880-6250'): 0.9997020953520708,
 ('ALB-CN-1870-15276', 'ALB-CN-1880-6254'): 0.9997020953520708,
 ('ALB-CN-1870-17565', 'ALB-CN-1880-6259'): 0.9997020953520708,
 ('ALB-CN-1870-11300', 'ALB-CN-1880-626'): 0.9997020953520708,
 ('ALB-CN-1870-15719', 'ALB-CN-1880-6260'): 0.9997020953520708,
 ('ALB-CN-1870-17565', 'ALB-CN-1880-6263'): 0.9997020953520708,
 ('ALB-CN-1870-14808', 'ALB-CN-1880-6272'): 0.9997020953520708,
 ('ALB-CN-1870-4997', 'ALB-CN-1880-6273'): 0.9997020953520708,
 ('ALB-CN-1870-9164', 'ALB-CN-1880-6274'): 0.9997020953520708,
 ('ALB-CN-1870-4619', 'ALB-CN-1880-6280'): 0.9997020953520708,
 ('ALB-CN-1870-4619', 'ALB-CN-1880-6284'): 0.9997020953520708,
 ('ALB-CN-1870-9444', 'ALB-CN-1880-6285'): 0.9997020953520708,
 ('ALB-CN-1870-14857', 'ALB-CN-1880-6286'): 0.999998835964552,
 ('ALB-CN-1870-365', 'ALB-CN-1880-6287'): 0.9997020953520708,
 ('ALB-CN-1870-14863', 'ALB-CN-1880-6291'): 0.9997020953520708,
 ('ALB-CN-1870-365', 'ALB-CN-1880-6292'): 0.9997020953520708,
 ('ALB-CN-1870-14870', 'ALB-CN-1880-6294'): 0.9999530711793492,
 ('ALB-CN-1870-6803', 'ALB-CN-1880-6299'): 0.9997020953520708,
 ('ALB-CN-1870-740', 'ALB-CN-1880-630'): 0.9999530711793492,
 ('ALB-CN-1870-2191', 'ALB-CN-1880-6304'): 0.9997020953520708,
 ('ALB-CN-1870-9139', 'ALB-CN-1880-6305'): 0.9997020953520708,
 ('ALB-CN-1870-16695', 'ALB-CN-1880-6307'): 0.9999926088816468,
 ('ALB-CN-1870-14878', 'ALB-CN-1880-6308'): 0.999998835964552,
 ('ALB-CN-1870-14832', 'ALB-CN-1880-6317'): 0.9999999909059626,
 ('ALB-CN-1870-16329', 'ALB-CN-1880-6319'): 0.3940365307413797,
 ('ALB-CN-1870-19352', 'ALB-CN-1880-632'): 0.9997020953520708,
 ('ALB-CN-1870-4408', 'ALB-CN-1880-6325'): 0.9997020953520708,
 ('ALB-CN-1870-14348', 'ALB-CN-1880-6326'): 0.9999530711793492,
 ('ALB-CN-1870-14886', 'ALB-CN-1880-6334'): 0.9997020953520708,
 ('ALB-CN-1870-14886', 'ALB-CN-1880-6335'): 0.9997020953520708,
 ('ALB-CN-1870-14759', 'ALB-CN-1880-6337'): 0.9999530711793492,
 ('ALB-CN-1870-9807', 'ALB-CN-1880-6341'): 0.9999530711793492,
 ('ALB-CN-1870-13827', 'ALB-CN-1880-6342'): 0.9999530711793492,
 ('ALB-CN-1870-14886', 'ALB-CN-1880-6343'): 0.999998835964552,
 ('ALB-CN-1870-4408', 'ALB-CN-1880-6344'): 0.9997020953520708,
 ('ALB-CN-1870-18669', 'ALB-CN-1880-6352'): 0.9997020953520708,
 ('ALB-CN-1870-14764', 'ALB-CN-1880-6359'): 0.9999999909059626,
 ('ALB-CN-1870-4871', 'ALB-CN-1880-6366'): 0.3940365307413797,
 ('ALB-CN-1870-11558', 'ALB-CN-1880-6367'): 0.9997020953520708,
 ('ALB-CN-1870-22500', 'ALB-CN-1880-6369'): 0.9997020953520708,
 ('ALB-CN-1870-15859', 'ALB-CN-1880-6370'): 0.3940365307413797,
 ('ALB-CN-1870-14306', 'ALB-CN-1880-6373'): 0.999998835964552,
 ('ALB-CN-1870-5223', 'ALB-CN-1880-6374'): 0.805027262406245,
 ('ALB-CN-1870-1934', 'ALB-CN-1880-6375'): 0.9997020953520708,
 ('ALB-CN-1870-14309', 'ALB-CN-1880-6376'): 0.999998835964552,
 ('ALB-CN-1870-15870', 'ALB-CN-1880-6377'): 0.3940365307413797,
 ('ALB-CN-1870-20834', 'ALB-CN-1880-6384'): 0.9997020953520708,
 ('ALB-CN-1870-9990', 'ALB-CN-1880-6385'): 0.3940365307413797,
 ('ALB-CN-1870-8083', 'ALB-CN-1880-6387'): 0.9999926088816468,
 ('ALB-CN-1870-15290', 'ALB-CN-1880-6391'): 0.9999530711793492,
 ('ALB-CN-1870-15091', 'ALB-CN-1880-6393'): 0.9997020953520708,
 ('ALB-CN-1870-17993', 'ALB-CN-1880-6397'): 0.9997020953520708,
 ('ALB-CN-1870-20620', 'ALB-CN-1880-6400'): 0.9997020953520708,
 ('ALB-CN-1870-20621', 'ALB-CN-1880-6402'): 0.9997020953520708,
 ('ALB-CN-1870-17893', 'ALB-CN-1880-6404'): 0.9999999909059626,
 ('ALB-CN-1870-14158', 'ALB-CN-1880-6407'): 0.9997020953520708,
 ('ALB-CN-1870-6884', 'ALB-CN-1880-6410'): 0.9999530711793492,
 ('ALB-CN-1870-9445', 'ALB-CN-1880-6416'): 0.9997020953520708,
 ('ALB-CN-1870-17455', 'ALB-CN-1880-6419'): 0.9999530711793492,
 ('ALB-CN-1870-22165', 'ALB-CN-1880-6422'): 0.9999926088816468,
 ('ALB-CN-1870-9649', 'ALB-CN-1880-6423'): 0.3940365307413797,
 ('ALB-CN-1870-22168', 'ALB-CN-1880-6424'): 0.999998835964552,
 ('ALB-CN-1870-22142', 'ALB-CN-1880-6437'): 0.9999999909059626,
 ('ALB-CN-1870-22143', 'ALB-CN-1880-6438'): 0.9999926088816468,
 ('ALB-CN-1870-15139', 'ALB-CN-1880-6439'): 0.9999530711793492,
 ('ALB-CN-1870-22146', 'ALB-CN-1880-6440'): 0.999998835964552,
 ('ALB-CN-1870-22147', 'ALB-CN-1880-6441'): 0.999998835964552,
 ('ALB-CN-1870-16337', 'ALB-CN-1880-6442'): 0.9997020953520708,
 ('ALB-CN-1870-16150', 'ALB-CN-1880-6443'): 0.9997020953520708,
 ('ALB-CN-1870-22150', 'ALB-CN-1880-6444'): 0.999998835964552,
 ('ALB-CN-1870-15645', 'ALB-CN-1880-6447'): 0.9997020953520708,
 ('ALB-CN-1870-15645', 'ALB-CN-1880-6448'): 0.9997020953520708,
 ('ALB-CN-1870-21044', 'ALB-CN-1880-6450'): 0.9999530711793492,
 ('ALB-CN-1870-16148', 'ALB-CN-1880-6452'): 0.9997020953520708,
 ('ALB-CN-1870-22165', 'ALB-CN-1880-6453'): 0.9997020953520708,
 ('ALB-CN-1870-9329', 'ALB-CN-1880-6455'): 0.9997020953520708,
 ('ALB-CN-1870-22127', 'ALB-CN-1880-6457'): 0.999998835964552,
 ('ALB-CN-1870-22133', 'ALB-CN-1880-6459'): 0.9999926088816468,
 ('ALB-CN-1870-9723', 'ALB-CN-1880-6460'): 0.3940365307413797,
 ('ALB-CN-1870-5176', 'ALB-CN-1880-6462'): 0.9997020953520708,
 ('ALB-CN-1870-4312', 'ALB-CN-1880-6463'): 0.999998835964552,
 ('ALB-CN-1870-20771', 'ALB-CN-1880-6464'): 0.9999530711793492,
 ('ALB-CN-1870-16149', 'ALB-CN-1880-6467'): 0.9997020953520708,
 ('ALB-CN-1870-22520', 'ALB-CN-1880-6468'): 0.9999926088816468,
 ('ALB-CN-1870-19781', 'ALB-CN-1880-6469'): 0.9997020953520708,
 ('ALB-CN-1870-19785', 'ALB-CN-1880-6470'): 0.9997020953520708,
 ('ALB-CN-1870-19782', 'ALB-CN-1880-6472'): 0.9999999909059626,
 ('ALB-CN-1870-19783', 'ALB-CN-1880-6473'): 0.999998835964552,
 ('ALB-CN-1870-19784', 'ALB-CN-1880-6474'): 0.999998835964552,
 ('ALB-CN-1870-19785', 'ALB-CN-1880-6475'): 0.999998835964552,
 ('ALB-CN-1870-16622', 'ALB-CN-1880-6478'): 0.9997020953520708,
 ('ALB-CN-1870-10089', 'ALB-CN-1880-6479'): 0.3940365307413797,
 ('ALB-CN-1870-5175', 'ALB-CN-1880-6481'): 0.9997020953520708,
 ('ALB-CN-1870-14887', 'ALB-CN-1880-6482'): 0.9997020953520708,
 ('ALB-CN-1870-3595', 'ALB-CN-1880-6485'): 0.9999530711793492,
 ('ALB-CN-1870-3603', 'ALB-CN-1880-6486'): 0.9999530711793492,
 ('ALB-CN-1870-8791', 'ALB-CN-1880-649'): 0.3940365307413797,
 ('ALB-CN-1870-9329', 'ALB-CN-1880-6499'): 0.9999926088816468,
 ('ALB-CN-1870-9649', 'ALB-CN-1880-6500'): 0.3940365307413797,
 ('ALB-CN-1870-22563', 'ALB-CN-1880-6511'): 0.9997020953520708,
 ('ALB-CN-1870-22282', 'ALB-CN-1880-6523'): 0.9999530711793492,
 ('ALB-CN-1870-18874', 'ALB-CN-1880-6525'): 0.9997020953520708,
 ('ALB-CN-1870-22498', 'ALB-CN-1880-6527'): 0.9997020953520708,
 ('ALB-CN-1870-18870', 'ALB-CN-1880-6528'): 0.9997020953520708,
 ('ALB-CN-1870-18871', 'ALB-CN-1880-6529'): 0.9997020953520708,
 ('ALB-CN-1870-9135', 'ALB-CN-1880-6530'): 0.9997020953520708,
 ('ALB-CN-1870-787', 'ALB-CN-1880-6531'): 0.9997020953520708,
 ('ALB-CN-1870-15139', 'ALB-CN-1880-6533'): 0.9999926088816468,
 ('ALB-CN-1870-22122', 'ALB-CN-1880-6537'): 0.9999530711793492,
 ('ALB-CN-1870-22558', 'ALB-CN-1880-6540'): 0.963258287003524,
 ('ALB-CN-1870-21642', 'ALB-CN-1880-6541'): 0.3940365307413797,
 ('ALB-CN-1870-22565', 'ALB-CN-1880-6542'): 0.9997020953520708,
 ('ALB-CN-1870-10310', 'ALB-CN-1880-6551'): 0.9997020953520708,
 ('ALB-CN-1870-10612', 'ALB-CN-1880-6553'): 0.805027262406245,
 ('ALB-CN-1870-19401', 'ALB-CN-1880-6555'): 0.9999926088816468,
 ('ALB-CN-1870-7577', 'ALB-CN-1880-6561'): 0.9997020953520708,
 ('ALB-CN-1870-17419', 'ALB-CN-1880-6565'): 0.9997020953520708,
 ('ALB-CN-1870-20685', 'ALB-CN-1880-6566'): 0.9997020953520708,
 ('ALB-CN-1870-20683', 'ALB-CN-1880-6570'): 0.9997020953520708,
 ('ALB-CN-1870-9572', 'ALB-CN-1880-658'): 0.9997020953520708,
 ('ALB-CN-1870-3601', 'ALB-CN-1880-6583'): 0.9997020953520708,
 ('ALB-CN-1870-13980', 'ALB-CN-1880-6589'): 0.9997020953520708,
 ('ALB-CN-1870-16893', 'ALB-CN-1880-6590'): 0.9997020953520708,
 ('ALB-CN-1870-16893', 'ALB-CN-1880-6592'): 0.9997020953520708,
 ('ALB-CN-1870-5479', 'ALB-CN-1880-6594'): 0.9997020953520708,
 ('ALB-CN-1870-20591', 'ALB-CN-1880-6607'): 0.9999999909059626,
 ('ALB-CN-1870-7453', 'ALB-CN-1880-6611'): 0.9997020953520708,
 ('ALB-CN-1870-21476', 'ALB-CN-1880-6617'): 0.9997020953520708,
 ('ALB-CN-1870-20674', 'ALB-CN-1880-6619'): 0.9999999909059626,
 ('ALB-CN-1870-20678', 'ALB-CN-1880-6622'): 0.9999999909059626,
 ('ALB-CN-1870-1934', 'ALB-CN-1880-6626'): 0.999998835964552,
 ('ALB-CN-1870-21085', 'ALB-CN-1880-6627'): 0.9997020953520708,
 ('ALB-CN-1870-5302', 'ALB-CN-1880-6628'): 0.9997020953520708,
 ('ALB-CN-1870-21533', 'ALB-CN-1880-6630'): 0.999998835964552,
 ('ALB-CN-1870-21536', 'ALB-CN-1880-6634'): 0.9997020953520708,
 ('ALB-CN-1870-21537', 'ALB-CN-1880-6636'): 0.9999926088816468,
 ('ALB-CN-1870-21538', 'ALB-CN-1880-6637'): 0.9999926088816468,
 ('ALB-CN-1870-4574', 'ALB-CN-1880-6643'): 0.9997020953520708,
 ('ALB-CN-1870-21213', 'ALB-CN-1880-6644'): 0.9997020953520708,
 ('ALB-CN-1870-21708', 'ALB-CN-1880-6645'): 0.9997020953520708,
 ('ALB-CN-1870-1765', 'ALB-CN-1880-666'): 0.3940365307413797,
 ('ALB-CN-1870-4194', 'ALB-CN-1880-6662'): 0.9997020953520708,
 ('ALB-CN-1870-13246', 'ALB-CN-1880-6679'): 0.9997020953520708,
 ('ALB-CN-1870-22569', 'ALB-CN-1880-6697'): 0.9997020953520708,
 ('ALB-CN-1870-22570', 'ALB-CN-1880-6698'): 0.9999530711793492,
 ('ALB-CN-1870-22570', 'ALB-CN-1880-6700'): 0.9997020953520708,
 ('ALB-CN-1870-21428', 'ALB-CN-1880-6708'): 0.9997020953520708,
 ('ALB-CN-1870-17672', 'ALB-CN-1880-6709'): 0.9999926088816468,
 ('ALB-CN-1870-16008', 'ALB-CN-1880-6710'): 0.9997020953520708,
 ('ALB-CN-1870-16622', 'ALB-CN-1880-6711'): 0.9997020953520708,
 ('ALB-CN-1870-15587', 'ALB-CN-1880-6712'): 0.9999926088816468,
 ('ALB-CN-1870-21875', 'ALB-CN-1880-6713'): 0.805027262406245,
 ('ALB-CN-1870-16093', 'ALB-CN-1880-6718'): 0.9997020953520708,
 ('ALB-CN-1870-6822', 'ALB-CN-1880-6721'): 0.3940365307413797,
 ('ALB-CN-1870-22350', 'ALB-CN-1880-6722'): 0.9997020953520708,
 ('ALB-CN-1870-6963', 'ALB-CN-1880-6727'): 0.9997020953520708,
 ('ALB-CN-1870-15801', 'ALB-CN-1880-6728'): 0.3940365307413797,
 ('ALB-CN-1870-14828', 'ALB-CN-1880-673'): 0.9999999909059626,
 ('ALB-CN-1870-22414', 'ALB-CN-1880-6730'): 0.9997020953520708,
 ('ALB-CN-1870-22561', 'ALB-CN-1880-6732'): 0.9997020953520708,
 ('ALB-CN-1870-22566', 'ALB-CN-1880-6733'): 0.9997020953520708,
 ('ALB-CN-1870-22565', 'ALB-CN-1880-6735'): 0.9997020953520708,
 ('ALB-CN-1870-22317', 'ALB-CN-1880-6736'): 0.9997020953520708,
 ('ALB-CN-1870-21579', 'ALB-CN-1880-6737'): 0.9997020953520708,
 ('ALB-CN-1870-21281', 'ALB-CN-1880-6738'): 0.9999926088816468,
 ('ALB-CN-1870-5760', 'ALB-CN-1880-6744'): 0.9997020953520708,
 ('ALB-CN-1870-20621', 'ALB-CN-1880-6747'): 0.9999530711793492,
 ('ALB-CN-1870-5760', 'ALB-CN-1880-6748'): 0.9999530711793492,
 ('ALB-CN-1870-21706', 'ALB-CN-1880-6757'): 0.9999530711793492,
 ('ALB-CN-1870-16634', 'ALB-CN-1880-6763'): 0.9997020953520708,
 ('ALB-CN-1870-16640', 'ALB-CN-1880-6766'): 0.9997020953520708,
 ('ALB-CN-1870-18961', 'ALB-CN-1880-677'): 0.9997020953520708,
 ('ALB-CN-1870-22461', 'ALB-CN-1880-6777'): 0.9997020953520708,
 ('ALB-CN-1870-22458', 'ALB-CN-1880-6779'): 0.9997020953520708,
 ('ALB-CN-1870-22229', 'ALB-CN-1880-6780'): 0.9997020953520708,
 ('ALB-CN-1870-10151', 'ALB-CN-1880-6785'): 0.9997020953520708,
 ('ALB-CN-1870-15856', 'ALB-CN-1880-6790'): 0.3940365307413797,
 ('ALB-CN-1870-22500', 'ALB-CN-1880-6791'): 0.9997020953520708,
 ('ALB-CN-1870-21605', 'ALB-CN-1880-6792'): 0.9999999909059626,
 ('ALB-CN-1870-15859', 'ALB-CN-1880-6794'): 0.3940365307413797,
 ('ALB-CN-1870-22146', 'ALB-CN-1880-6797'): 0.9997020953520708,
 ('ALB-CN-1870-21313', 'ALB-CN-1880-6801'): 0.9997020953520708,
 ('ALB-CN-1870-21758', 'ALB-CN-1880-6805'): 0.3940365307413797,
 ('ALB-CN-1870-22523', 'ALB-CN-1880-6806'): 0.9997020953520708,
 ('ALB-CN-1870-3455', 'ALB-CN-1880-6807'): 0.9997020953520708,
 ('ALB-CN-1870-8930', 'ALB-CN-1880-6810'): 0.9997020953520708,
 ('ALB-CN-1870-9247', 'ALB-CN-1880-6814'): 0.9997020953520708,
 ('ALB-CN-1870-22517', 'ALB-CN-1880-6830'): 0.9997020953520708,
 ('ALB-CN-1870-22506', 'ALB-CN-1880-6831'): 0.9997020953520708,
 ('ALB-CN-1870-1686', 'ALB-CN-1880-6833'): 0.9997020953520708,
 ('ALB-CN-1870-21079', 'ALB-CN-1880-6834'): 0.9999530711793492,
 ('ALB-CN-1870-21145', 'ALB-CN-1880-6835'): 0.999998835964552,
 ('ALB-CN-1870-21081', 'ALB-CN-1880-6836'): 0.9999999909059626,
 ('ALB-CN-1870-12565', 'ALB-CN-1880-6837'): 0.9997020953520708,
 ('ALB-CN-1870-19869', 'ALB-CN-1880-6840'): 0.9999926088816468,
 ('ALB-CN-1870-21660', 'ALB-CN-1880-6841'): 0.9997020953520708,
 ('ALB-CN-1870-22325', 'ALB-CN-1880-6845'): 0.9997020953520708,
 ('ALB-CN-1870-22560', 'ALB-CN-1880-6853'): 0.999998835964552,
 ('ALB-CN-1870-22565', 'ALB-CN-1880-6855'): 0.9997020953520708,
 ('ALB-CN-1870-22554', 'ALB-CN-1880-6856'): 0.3940365307413797,
 ('ALB-CN-1870-5176', 'ALB-CN-1880-6857'): 0.9997020953520708,
 ('ALB-CN-1870-1605', 'ALB-CN-1880-6858'): 0.9997020953520708,
 ('ALB-CN-1870-10406', 'ALB-CN-1880-686'): 0.9997020953520708,
 ('ALB-CN-1870-4312', 'ALB-CN-1880-6861'): 0.999998835964552,
 ('ALB-CN-1870-16337', 'ALB-CN-1880-6864'): 0.9997020953520708,
 ('ALB-CN-1870-22522', 'ALB-CN-1880-6865'): 0.999998835964552,
 ('ALB-CN-1870-22523', 'ALB-CN-1880-6866'): 0.9999926088816468,
 ('ALB-CN-1870-22524', 'ALB-CN-1880-6867'): 0.963258287003524,
 ('ALB-CN-1870-22165', 'ALB-CN-1880-6870'): 0.9997020953520708,
 ('ALB-CN-1870-21989', 'ALB-CN-1880-6878'): 0.999998835964552,
 ('ALB-CN-1870-7711', 'ALB-CN-1880-689'): 0.9997020953520708,
 ('ALB-CN-1870-21313', 'ALB-CN-1880-6890'): 0.9999530711793492,
 ('ALB-CN-1870-16337', 'ALB-CN-1880-6891'): 0.9997020953520708,
 ('ALB-CN-1870-22333', 'ALB-CN-1880-6895'): 0.9997020953520708,
 ('ALB-CN-1870-769', 'ALB-CN-1880-6896'): 0.9997020953520708,
 ('ALB-CN-1870-21001', 'ALB-CN-1880-6897'): 0.9999999909059626,
 ('ALB-CN-1870-21002', 'ALB-CN-1880-6898'): 0.999998835964552,
 ('ALB-CN-1870-22284', 'ALB-CN-1880-6899'): 0.9999926088816468,
 ('ALB-CN-1870-21005', 'ALB-CN-1880-6900'): 0.9999530711793492,
 ('ALB-CN-1870-15435', 'ALB-CN-1880-6907'): 0.9997020953520708,
 ('ALB-CN-1870-21839', 'ALB-CN-1880-6909'): 0.9999926088816468,
 ('ALB-CN-1870-21840', 'ALB-CN-1880-6910'): 0.999998835964552,
 ('ALB-CN-1870-21841', 'ALB-CN-1880-6912'): 0.999998835964552,
 ('ALB-CN-1870-20547', 'ALB-CN-1880-6915'): 0.9997020953520708,
 ('ALB-CN-1870-21882', 'ALB-CN-1880-6918'): 0.9999926088816468,
 ('ALB-CN-1870-15919', 'ALB-CN-1880-6919'): 0.999998835964552,
 ('ALB-CN-1870-10078', 'ALB-CN-1880-6922'): 0.9997020953520708,
 ('ALB-CN-1870-20729', 'ALB-CN-1880-6924'): 0.9999999909059626,
 ('ALB-CN-1870-20730', 'ALB-CN-1880-6925'): 0.9999999909059626,
 ('ALB-CN-1870-9445', 'ALB-CN-1880-6926'): 0.9999530711793492,
 ('ALB-CN-1870-21289', 'ALB-CN-1880-6928'): 0.3940365307413797,
 ('ALB-CN-1870-20727', 'ALB-CN-1880-6930'): 0.9997020953520708,
 ('ALB-CN-1870-19337', 'ALB-CN-1880-6932'): 0.9999530711793492,
 ('ALB-CN-1870-5119', 'ALB-CN-1880-6934'): 0.9997020953520708,
 ('ALB-CN-1870-10375', 'ALB-CN-1880-6935'): 0.9997020953520708,
 ('ALB-CN-1870-10165', 'ALB-CN-1880-6936'): 0.9997020953520708,
 ('ALB-CN-1870-19754', 'ALB-CN-1880-6943'): 0.9999530711793492,
 ('ALB-CN-1870-19755', 'ALB-CN-1880-6945'): 0.9999999909059626,
 ('ALB-CN-1870-12161', 'ALB-CN-1880-6947'): 0.9997020953520708,
 ('ALB-CN-1870-15370', 'ALB-CN-1880-695'): 0.9997020953520708,
 ('ALB-CN-1870-21226', 'ALB-CN-1880-6953'): 0.9997020953520708,
 ('ALB-CN-1870-6869', 'ALB-CN-1880-6954'): 0.9997020953520708,
 ('ALB-CN-1870-6863', 'ALB-CN-1880-6956'): 0.9997020953520708,
 ('ALB-CN-1870-3182', 'ALB-CN-1880-6962'): 0.9999926088816468,
 ('ALB-CN-1870-22435', 'ALB-CN-1880-6967'): 0.9997020953520708,
 ('ALB-CN-1870-14214', 'ALB-CN-1880-697'): 0.9997020953520708,
 ('ALB-CN-1870-9329', 'ALB-CN-1880-6973'): 0.9997020953520708,
 ('ALB-CN-1870-16149', 'ALB-CN-1880-6974'): 0.9997020953520708,
 ('ALB-CN-1870-22169', 'ALB-CN-1880-6976'): 0.9999999909059626,
 ('ALB-CN-1870-19741', 'ALB-CN-1880-6979'): 0.9997020953520708,
 ('ALB-CN-1870-16863', 'ALB-CN-1880-6980'): 0.963258287003524,
 ('ALB-CN-1870-19459', 'ALB-CN-1880-6981'): 0.9997020953520708,
 ('ALB-CN-1870-21154', 'ALB-CN-1880-6982'): 0.9997020953520708,
 ('ALB-CN-1870-10089', 'ALB-CN-1880-6984'): 0.9997020953520708,
 ('ALB-CN-1870-6153', 'ALB-CN-1880-700'): 0.999998835964552,
 ('ALB-CN-1870-8328', 'ALB-CN-1880-7006'): 0.963258287003524,
 ('ALB-CN-1870-8323', 'ALB-CN-1880-7009'): 0.805027262406245,
 ('ALB-CN-1870-6159', 'ALB-CN-1880-701'): 0.9997020953520708,
 ('ALB-CN-1870-22435', 'ALB-CN-1880-7013'): 0.9997020953520708,
 ('ALB-CN-1870-22437', 'ALB-CN-1880-7016'): 0.9997020953520708,
 ('ALB-CN-1870-19774', 'ALB-CN-1880-7019'): 0.999998835964552,
 ('ALB-CN-1870-6160', 'ALB-CN-1880-702'): 0.999998835964552,
 ('ALB-CN-1870-4253', 'ALB-CN-1880-7020'): 0.9997020953520708,
 ('ALB-CN-1870-5675', 'ALB-CN-1880-7024'): 0.9997020953520708,
 ('ALB-CN-1870-19800', 'ALB-CN-1880-7028'): 0.9997020953520708,
 ('ALB-CN-1870-6161', 'ALB-CN-1880-703'): 0.999998835964552,
 ('ALB-CN-1870-19838', 'ALB-CN-1880-7032'): 0.9999999909059626,
 ('ALB-CN-1870-19837', 'ALB-CN-1880-7033'): 0.9999999909059626,
 ('ALB-CN-1870-16756', 'ALB-CN-1880-7039'): 0.3940365307413797,
 ('ALB-CN-1870-19844', 'ALB-CN-1880-7056'): 0.9997020953520708,
 ('ALB-CN-1870-22574', 'ALB-CN-1880-7057'): 0.9997020953520708,
 ('ALB-CN-1870-22021', 'ALB-CN-1880-7061'): 0.999998835964552,
 ('ALB-CN-1870-3032', 'ALB-CN-1880-7064'): 0.9997020953520708,
 ('ALB-CN-1870-15956', 'ALB-CN-1880-7065'): 0.9997020953520708,
 ('ALB-CN-1870-14122', 'ALB-CN-1880-707'): 0.9999530711793492,
 ('ALB-CN-1870-5176', 'ALB-CN-1880-7074'): 0.9997020953520708,
 ('ALB-CN-1870-9688', 'ALB-CN-1880-7077'): 0.3940365307413797,
 ('ALB-CN-1870-14123', 'ALB-CN-1880-708'): 0.999998835964552,
 ('ALB-CN-1870-21415', 'ALB-CN-1880-7082'): 0.9999926088816468,
 ('ALB-CN-1870-948', 'ALB-CN-1880-7083'): 0.3940365307413797,
 ('ALB-CN-1870-921', 'ALB-CN-1880-7084'): 0.9997020953520708,
 ('ALB-CN-1870-996', 'ALB-CN-1880-7087'): 0.9997020953520708,
 ('ALB-CN-1870-996', 'ALB-CN-1880-7088'): 0.9997020953520708,
 ('ALB-CN-1870-10049', 'ALB-CN-1880-7089'): 0.9997020953520708,
 ('ALB-CN-1870-14124', 'ALB-CN-1880-709'): 0.999998835964552,

In [10]:
# Build a function to get relatives_match_probability
def get_relatives_match_probability(row):
    # Get the two sets of relatives
    relatives_l = row['relatives_l']
    relatives_r = row['relatives_r']
    # If the left side (1870 census) has no relatives, return nan
    if not isinstance(relatives_l, set) or not isinstance(relatives_r, set): # Also nan if no right relatives (nothing to compare)
        return np.nan
    # Create an empty list to hold best match probabilities
    best_probs = []
    # For each 1870 relative of all 1870 relatives
    for rel_l in relatives_l:
        # Get all non-nan match probabilities
        probs = [
            p for rel_r in relatives_r
            if not np.isnan(p := match_lookup.get((rel_l, rel_r), np.nan))
        ]
        # If no valid matches, append nan
        best_probs.append(max(probs) if probs else np.nan)
    # Return mean of best match probabilities (or nan)
    return np.nanmean(best_probs) if best_probs else np.nan

In [11]:
# Apply get_relatives_match_probability to matches
matches['relatives_match_probability'] = matches.apply(get_relatives_match_probability, axis=1)

/var/folders/js/d_qzf0bs4v1gw_dwxd4bhx7h0000gp/T/ipykernel_2262/3885961802.py:21: RuntimeWarning: Mean of empty slice
  return np.nanmean(best_probs) if best_probs else np.nan

In [15]:
# Write matches to CSV w/ relatives_match_probability
matches_subset = matches[['unique_id_l', 'unique_id_r', 'match_probability', 'relatives_match_probability']]
matches_subset.to_csv('boosted_preds.csv', index=False)

In [28]:
# Remove all NAs for relatives_match_probability
matches_no_nas = matches.copy().dropna(subset=['relatives_match_probability'])

In [30]:
# Display matches with relatives_match_probability
matches_no_nas.head(n=20)

,match_probability,unique_id_l,unique_id_r,relatives_l,relatives_r,relatives_match_probability
91,1.000000,ALB-CN-1870-22142,ALB-CN-1880-6437,{ALB-CN-1870-22147},"{ALB-CN-1880-6438, ALB-CN-1880-6442, ALB-CN-18...",0.999999
95,0.999999,ALB-CN-1870-22147,ALB-CN-1880-6441,{ALB-CN-1870-22142},{ALB-CN-1880-6437},1.000000
115,1.000000,ALB-CN-1870-19782,ALB-CN-1880-6472,{ALB-CN-1870-19778},{ALB-CN-1880-6469},1.000000
128,0.999702,ALB-CN-1870-22563,ALB-CN-1880-6511,{ALB-CN-1870-22560},"{ALB-CN-1880-6514, ALB-CN-1880-6512, ALB-CN-18...",0.394037
154,1.000000,ALB-CN-1870-20591,ALB-CN-1880-6607,"{ALB-CN-1870-20596, ALB-CN-1870-20593}","{ALB-CN-1880-6609, ALB-CN-1880-6611, ALB-CN-18...",0.697018
164,0.999993,ALB-CN-1870-21537,ALB-CN-1880-6636,{ALB-CN-1870-21531},{ALB-CN-1880-6634},0.999999
205,0.394037,ALB-CN-1870-15856,ALB-CN-1880-6790,{ALB-CN-1870-15859},"{ALB-CN-1880-6793, ALB-CN-1880-6794, ALB-CN-18...",0.394037
208,0.394037,ALB-CN-1870-15859,ALB-CN-1880-6794,{ALB-CN-1870-15856},{ALB-CN-1880-6790},0.394037
226,0.999999,ALB-CN-1870-22560,ALB-CN-1880-6853,"{ALB-CN-1870-22563, ALB-CN-1870-22565}","{ALB-CN-1880-6855, ALB-CN-1880-6856, ALB-CN-18...",0.999702
227,0.999702,ALB-CN-1870-22565,ALB-CN-1880-6855,{ALB-CN-1870-22560},{ALB-CN-1880-6853},0.999999
234,0.999999,ALB-CN-1870-22522,ALB-CN-1880-6865,{ALB-CN-1870-22518},{ALB-CN-1880-6863},0.805027
245,0.999999,ALB-CN-1870-21002,ALB-CN-1880-6898,{ALB-CN-1870-20997},{ALB-CN-1880-6894},0.999953
254,0.999999,ALB-CN-1870-15919,ALB-CN-1880-6919,{ALB-CN-1870-15913},{ALB-CN-1880-6915},0.999702
296,1.000000,ALB-CN-1870-19837,ALB-CN-1880-7033,{ALB-CN-1870-19834},{ALB-CN-1880-7030},0.805027
391,0.999702,ALB-CN-1870-769,ALB-CN-1880-7363,{ALB-CN-1870-762},"{ALB-CN-1880-7369, ALB-CN-1880-7371, ALB-CN-18...",0.999702
392,0.999702,ALB-CN-1870-769,ALB-CN-1880-7366,{ALB-CN-1870-762},{ALB-CN-1880-7363},0.999702
478,0.999993,ALB-CN-1870-20722,ALB-CN-1880-7565,{ALB-CN-1870-20720},{ALB-CN-1880-7563},0.992488
493,0.999702,ALB-CN-1870-5656,ALB-CN-1880-7623,"{ALB-CN-1870-5658, ALB-CN-1870-5661}","{ALB-CN-1880-7624, ALB-CN-1880-7625}",0.999702
494,0.999702,ALB-CN-1870-5661,ALB-CN-1880-7625,{ALB-CN-1870-5656},{ALB-CN-1880-7623},0.999702
500,0.999702,ALB-CN-1870-18076,ALB-CN-1880-7640,{ALB-CN-1870-18074},{ALB-CN-1880-7637},0.394037

In [34]:
# Look at Dabney Johnson
# FIlter for his mention id, sort on match_probability then relatives_match_probability (descending), and display top 10
matches_no_nas[matches_no_nas['unique_id_l'] == 'ALB-CN-1870-1688'].sort_values(['match_probability', 'relatives_match_probability'], ascending=False).head(n=10)

,match_probability,unique_id_l,unique_id_r,relatives_l,relatives_r,relatives_match_probability
20376,1.000000,ALB-CN-1870-1688,ALB-CN-1880-22721,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-22722, ALB-CN-1880-22735, ALB-CN-...",0.999851
18871123,0.999993,ALB-CN-1870-1688,ALB-CN-1880-25680,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-25683, ALB-CN-1880-25681, ALB-CN-...",0.963258
17084360,0.999953,ALB-CN-1870-1688,ALB-CN-1880-22460,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-22464, ALB-CN-1880-22461, ALB-CN-...",0.678647
1134782,0.999953,ALB-CN-1870-1688,ALB-CN-1880-7003,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-7009, ALB-CN-1880-7004, ALB-CN-18...",0.394037
1134911,0.999702,ALB-CN-1870-1688,ALB-CN-1880-10250,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-10252, ALB-CN-1880-10251, ALB-CN-...",0.963258
15304153,0.999702,ALB-CN-1870-1688,ALB-CN-1880-18656,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-18659, ALB-CN-1880-18658, ALB-CN-...",0.963258
20812079,0.999702,ALB-CN-1870-1688,ALB-CN-1880-28345,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-28349, ALB-CN-1880-28350, ALB-CN-...",0.963258
4591700,0.999702,ALB-CN-1870-1688,ALB-CN-1880-15526,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-15529, ALB-CN-1880-15531, ALB-CN-...",0.884143
6417960,0.999702,ALB-CN-1870-1688,ALB-CN-1880-12983,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-12988, ALB-CN-1880-12986, ALB-CN-...",0.884143
24650299,0.999702,ALB-CN-1870-1688,ALB-CN-1880-4538,"{ALB-CN-1870-1691, ALB-CN-1870-1694}","{ALB-CN-1880-4540, ALB-CN-1880-4547, ALB-CN-18...",0.884143